-- Run this in the Supabase SQL Editor

-- 1. Create Students Table
create table students (
  id bigint generated by default as identity primary key,
  name text not null
);

-- 2. Create Attendance Table
create table attendance (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  date_index int not null,
  status int default 0,
  unique(student_id, date_index)
);

-- 3. Enable Realtime
alter publication supabase_realtime add table attendance;

-- 4. Insert Initial Data
insert into students (name) values 
  ('배다희'), ('손여원'), ('김태린'), ('현요섭'), ('김승우'), 
  ('이은총'), ('조영광'), ('문하은'), ('최예인'), ('로이'), 
  ('서다현'), ('사예한'), ('이다율'), ('방태산'), ('이은서'), 
  ('민유진'), ('이태은'), ('허진주'), ('오나윤'), ('시온');

-- 5. Initialize Attendance (Optional, app handles empty states, but good for consistency)
-- This part is tricky in pure SQL without a loop function, 
-- but the app code handles "missing" attendance records by defaulting to 0.
